# order_0: assembly
# order_1: assembly
# parts on belt: no
# parts in bins: no
# challenges:
# - High-priority order

options:
  insert_models_over_bins: false
  insert_models_over_stations: false
  belt_population_cycles: 0
  gazebo_state_logging: false
time_limit: -1

agv_infos:
  agv1:
    location: ks1
  agv2:
    location: as2
    products:
      part_0:
        type: assembly_battery_red
        pose:
          xyz: [0.0, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: assembly_pump_red
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 0]
  agv3:
    location: ks3
  agv4:
    location: as4
    products:
      part_0:
        type: assembly_battery_blue
        pose:
          xyz: [0.0, -0.15, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 0]
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1
    assembly_robot_health: 1
    announcement_condition: time
    announcement_condition_value: 0.0
    assembly:
      shipment_count: 1
      stations: [as4]
      products:
        part_0:
          type: assembly_pump_blue
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [0, 0, 'pi']
        part_1:
          type: assembly_battery_blue
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]

  order_1:
    priority: 3
    kitting_robot_health: 1 ## Released 2021, May 28
    assembly_robot_health: 1 
    announcement_condition: unwanted_products
    announcement_condition_value: 1
    assembly:
      shipment_count: 1
      stations: [as2]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_battery_red
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]





